import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { afterAll, describe, expect, it } from 'vitest';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { composeProfiles, enabledPlatforms, openInstall, resolveInstallDir } from '../src/install';
import { readEnvFile, writeEnvFile } from '../src/env-file';
import { writeConfigFile } from '../src/config-file';
import { COMPOSE_FILE } from '../src/compose-file';

const root = await mkdtemp(join(tmpdir(), 'telecord-ingestion-install-'));
const home = join(root, 'home');

afterAll(async () => {
	await rm(root, { recursive: true, force: true });
});

const template = await readFile(join(import.meta.dirname, '../../compose.yml'), 'utf8');

describe('COMPOSE_FILE', () => {
	it('is the repository compose file under a header pointing at compose.override.yml', () => {
		expect(COMPOSE_FILE.startsWith('# Generated by telecord-ingestion')).toBe(true);
		expect(COMPOSE_FILE).toContain('compose.override.yml');
		expect(COMPOSE_FILE.endsWith(template)).toBe(true);
	});
});

describe('resolveInstallDir', () => {
	it('takes the given directory, expanding ~', () => {
		expect(resolveInstallDir('~/elsewhere', root, home)).toBe(join(home, 'elsewhere'));
		expect(resolveInstallDir('relative', root, home)).toBe(join(root, 'relative'));
	});

	it('uses the current directory when it holds an install', async () => {
		const cwd = await mkdtemp(join(root, 'cwd-'));

		expect(resolveInstallDir(undefined, cwd, home)).toBe(join(home, 'telecord-ingestion'));

		await writeFile(join(cwd, 'compose.yml'), '');

		expect(resolveInstallDir(undefined, cwd, home)).toBe(cwd);
	});
});

describe('openInstall', () => {
	it('regenerates compose.yml and never touches compose.override.yml', async () => {
		const dir = join(root, 'existing');
		const override = 'services:\n    discord:\n        image: local/discord:test\n';

		await mkdir(dir);
		await writeFile(join(dir, 'config.toml'), '');
		await writeFile(join(dir, 'compose.yml'), 'services: {}\n');
		await writeFile(join(dir, 'compose.override.yml'), override);
		await openInstall(dir);

		expect(await readFile(join(dir, 'compose.yml'), 'utf8')).toBe(COMPOSE_FILE);
		expect(await readFile(join(dir, 'compose.override.yml'), 'utf8')).toBe(override);
	});

	it('refuses a directory without config.toml unless creating it', async () => {
		const dir = join(root, 'new', 'install');

		await expect(openInstall(dir)).rejects.toThrow(`Failed to find an install in ${dir}`);
		await openInstall(dir, true);

		expect(await readFile(join(dir, 'compose.yml'), 'utf8')).toBe(COMPOSE_FILE);
	});
});

describe('writeConfigFile', () => {
	it('rewrites the same file in place, readable by its owner only', async () => {
		const path = join(root, 'config.toml');

		await writeConfigFile(path, '[discord]\ntoken = "a"\n');

		const before = await stat(path);

		await writeConfigFile(path, '[discord]\n');

		const after = await stat(path);

		expect(await readFile(path, 'utf8')).toBe('[discord]\n');
		expect(after.ino).toBe(before.ino);

		if (process.platform !== 'win32') {
			expect(after.mode & 0o777).toBe(0o600);
		}
	});
});

describe('.env', () => {
	it('round-trips the install settings and reads the enabled platforms', async () => {
		const path = join(root, '.env');

		await writeEnvFile(path, {
			COMPOSE_PROFILES: 'telegram,discord,updater',
			HOST_UID: undefined,
			CHECK_INTERVAL: '12h',
		});

		const env = await readEnvFile(path);

		expect(await readFile(path, 'utf8')).toBe(
			'COMPOSE_PROFILES=telegram,discord,updater\nCHECK_INTERVAL=12h\n',
		);
		expect(enabledPlatforms(env ?? {})).toEqual(['telegram', 'discord']);
		expect(await readEnvFile(join(root, 'missing.env'))).toBeUndefined();
	});

	it('reads hand-edited profiles, ignoring spaces and empty entries', () => {
		expect(composeProfiles({ COMPOSE_PROFILES: ' telegram , updater,' })).toEqual([
			'telegram',
			'updater',
		]);
		expect(composeProfiles({})).toEqual([]);
	});
});
