import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import template from '../../compose.yml' with { type: 'text' };

const HEADER = `# Generated by telecord-ingestion, which rewrites this file on every run.
# Put your own changes in compose.override.yml, which Compose merges over this file.

`;

/** The install's `compose.yml`: the repository's compose file under a header saying not to edit it. */
export const COMPOSE_FILE = HEADER + template;

/**
 * Writes the install's `compose.yml`, replacing whatever an older CLI or the
 * user left there. `compose.override.yml` is the user's and never written.
 *
 * @param dir - The install directory.
 */
export async function writeComposeFile(dir: string): Promise<void> {
	await writeFile(join(dir, 'compose.yml'), COMPOSE_FILE);
}
